// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyEEBx38YdCoEQo7JqzsbBlDzZYxGdeRE',
    appId: '1:621556283875:web:46c8a13af1f9f7aecc88d6',
    messagingSenderId: '621556283875',
    projectId: 'pregancy-c3863',
    authDomain: 'pregancy-c3863.firebaseapp.com',
    storageBucket: 'pregancy-c3863.appspot.com',
    measurementId: 'G-YQ7GDY4ZDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7m7C61dtiX3ivft-Opo77tjzsoQCyO0s',
    appId: '1:621556283875:android:1bacefa829d981b6cc88d6',
    messagingSenderId: '621556283875',
    projectId: 'pregancy-c3863',
    storageBucket: 'pregancy-c3863.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwwr8B2_3iAW2AtCj0We32uYuZpS-_gcw',
    appId: '1:621556283875:ios:c23dd107940e981fcc88d6',
    messagingSenderId: '621556283875',
    projectId: 'pregancy-c3863',
    storageBucket: 'pregancy-c3863.appspot.com',
    iosClientId: '621556283875-ejm47nhetvcfmn3rpe7api87e0hgonfd.apps.googleusercontent.com',
    iosBundleId: 'com.example.pregancy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwwr8B2_3iAW2AtCj0We32uYuZpS-_gcw',
    appId: '1:621556283875:ios:c23dd107940e981fcc88d6',
    messagingSenderId: '621556283875',
    projectId: 'pregancy-c3863',
    storageBucket: 'pregancy-c3863.appspot.com',
    iosClientId: '621556283875-ejm47nhetvcfmn3rpe7api87e0hgonfd.apps.googleusercontent.com',
    iosBundleId: 'com.example.pregancy',
  );
}
